### ISSUE TITLE
how can i get the correspondence index?

### ISSUE THREAD

**Issue by caijinana** [ThibaultGROUEIX/3D-CODED#46] opened 2021-12-09 06:42 UTC

**Comment by caijinana** [comment] 2021-12-17 06:59
I was expecting to get pairs of points {(q_r, q_t)}

**Comment by ThibaultGROUEIX** [comment] 2022-01-11 16:36
Hi @caijinana,
I do not understand your question. Can you clarify which part of the code you are referring to and what you are trying to achieve?
Best regards

**Comment by caijinana** [comment] 2022-02-08 07:05
Hi@ThibaultGROUEIX,i want to say how to get the correspondence point {(qr,qt)}where qr is a point on the source model and qt is   a point on the target model, i want to get a random point and it's correspindence point. i test on difference dataset but all get terrible result. i found it worked good only test on Faust_dataset. How could i solve the problem?
I use the following code to get the correspondence:
`            if self.project_on_target:
                print("projection on target...")
                self.neigh.fit(target.vertices)
                idx_knn = self.neigh.kneighbors(closest_points, return_distance=False)
                closest_points = target.vertices[idx_knn]
                np.savetxt("results/correspondences_tar.txt", idx_knn, fmt='%d')
                closest_points = np.mean(closest_points, 1, keepdims=False)
     with open("correspondences_tar.txt") as f:
    cpt = 0
    for line in f:
        cpt += 1
        if cpt == 3377 or cpt==4432 or cpt==5566or cpt==5524or cpt==5404or cpt==5411 or cpt==3519 or cpt==5520 or cpt==5492 or cpt==4403 or cpt==6138 or cpt==7168 or cpt==6122 or cpt==8244\
            or cpt==8244 or cpt==8138 or cpt==8145 or cpt==6280 or cpt==8239 or cpt==8221 or cpt==7139:
            result=(cpt,int(line))
            print(result)`

**Comment by caijinana** [comment] 2022-02-08 07:06
hi @ThibaultGROUEIX

**Comment by ThibaultGROUEIX** [comment] 2022-02-08 08:42
Hi @caijinana ,

The model should be robust across datasets. Can share a meshlab plot of a sample of your new dataset overlayed with one of Faust meshes?

things to look for :
- orientation of your new data
- scale of your new data

Best regards;
Thibault

**Comment by caijinana** [comment] 2022-02-08 08:56
i used smplx model as input A ,another smplx model as input b,but get terrible rusult.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Hi @caijinana ,
 
The model should be robust across datasets. Can share a meshlab plot of a sample of your new dataset overlayed with one of Faust meshes?
 
things to look for :
  
orientation of your new data
 
scale of your new data
  
Best regards;
 Thibault
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-08 08:57
@ThibaultGROUEIX

**Comment by ThibaultGROUEIX** [comment] 2022-02-08 09:01
Can you share a meshlab plot of a sample of your new dataset overlayed with one of Faust meshes?

**Comment by caijinana** [comment] 2022-02-08 09:08
Sorry i don't know how to get that ,this is my dataset&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/3D-CODED"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Can you share a meshlab plot of a sample of your new dataset overlayed with one of Faust meshes?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-08 09:17
I think that your orientation is likely wrong. The simple way to check this is to open jointly a faust mesh and an smplx model in any 3D viewer of your choice. MeshLab is a free software for visualisation but you could use your own viewer if it's easier.

**Comment by caijinana** [comment] 2022-02-08 09:26
i have checked ,my orientation is same as faust mesh
[result_2.8.zip](https://github.com/ThibaultGROUEIX/3D-CODED/files/8022407/result_2.8.zip)
.

**Comment by caijinana** [comment] 2022-02-08 09:27
the result_2.8.zip  is the correspondence result.

**Comment by ThibaultGROUEIX** [comment] 2022-02-08 10:04
Based on the shapes and poses I am seing for source and target, in my experience, 3D-CODED would definitely work. 
Please share a screenshot of your orientation check.

**Comment by ThibaultGROUEIX** [comment] 2022-02-08 10:18
Or just send me as OBJ or PLY:
- Source new dataset
- Target new dataset
- Faust sample

**Comment by caijinana** [comment] 2022-02-09 01:07
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Based on the shapes and poses I am seing for source and target, in my experience, 3D-CODED would definitely work.
 Please share a screenshot of your orientation check.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 01:18
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Or just send me as OBJ or PLY:
  
Source new dataset
 
Target new dataset
 
Faust sample
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 01:26
3D-CODED could get great reconstrucct target model,but as you see in result_2.8.zip,i find some correspondence&nbsp; points in source model and target model,but get terrible result.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Based on the shapes and poses I am seing for source and target, in my experience, 3D-CODED would definitely work.
 Please share a screenshot of your orientation check.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 02:43
![Uploading 微信图片_20220209091719.png…]()

**Comment by caijinana** [comment] 2022-02-09 06:45
[Uploading data.zip…]()

**Comment by caijinana** [comment] 2022-02-09 06:46
@ThibaultGROUEIX

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 09:05
I can download neither of those links unfortunately.
To move forward, can you please upload these OBJs (only this because I don't know your naming conventions and I cannot interpret your previous ZIP). ? 
* Source new dataset
* Source new dataset Reconstructed
* Target new dataset
* Target new dataset Reconstructed
* Faust sample

**Comment by caijinana** [comment] 2022-02-09 09:18
sorry i have named, but i network is terrible,i will upload again,thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月9日(星期三) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
I can download neither of those links unfortunately.
 To move forward, can you please upload these OBJs (only this because I don't know your naming conventions and I cannot interpret your previous ZIP). ?
  
Source new dataset
 
Source new dataset Reconstructed
 
Target new dataset
 
Target new dataset Reconstructed
 
Faust sample
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 09:37
sorry i don't know why i can't upload the data.zip again, i have try many times,but got error,the previous zip is:
result_2.8\result\result_1:
source.obj is Source new dataset ,it is a smplx model
target_1.obj is Target new dataset ,it is a smplx model
corres_1.txt some correspondences point idx in source and target



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/3D-CODED"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
I can download neither of those links unfortunately.
 To move forward, can you please upload these OBJs (only this because I don't know your naming conventions and I cannot interpret your previous ZIP). ?
  
Source new dataset
 
Source new dataset Reconstructed
 
Target new dataset
 
Target new dataset Reconstructed
 
Faust sample
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 10:37
Ok but this zip is missing the FAUST model and the 3D-CODED reconstructions.

**Comment by caijinana** [comment] 2022-02-09 10:56
sorry i still can't upload data, could you get a Faust model yourself?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月9日(星期三) 晚上6:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Ok but this zip is missing the FAUST model and the 3D-CODED reconstructions.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 11:38
![r](https://user-images.githubusercontent.com/64821543/153192563-4a9f2e4f-353b-440d-8900-c04e36dc3c64.jpg)

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 11:40
great, this looks reasonable indeed, can you show the reconstructions and show the axis?

**Comment by caijinana** [comment] 2022-02-09 11:44
![reconstruction](https://user-images.githubusercontent.com/64821543/153193537-c25c3940-301b-4d73-9604-50680a351936.png)

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 11:49
The reconstructions are pretty good and the color code suggests that the correspondence are pretty good. 
Are you using my script `compute_correspondences`?
https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/inference/correspondences.py#L71

**Comment by caijinana** [comment] 2022-02-09 11:52
yes,i used and the finally correspondences.ply is pretty good,but the  point correspondences is terrible 
![934523df4bac07d71c0a10b5a263ed4](https://user-images.githubusercontent.com/64821543/153195201-98cc0ace-8490-48c2-aa7e-f53b9004b2c8.png)

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 11:57
Please always source what you say to help me helping you. Can you show the final `correspondences.ply`. How can I interpret the list you sent? What is supposed to be the ground truth?

**Comment by caijinana** [comment] 2022-02-09 12:06
i just want to get the correspondence point like what the paper said.（3377，3375）is a pair of correspondece point.for example (3377,3375),3373 is a point index in source model and 3375 is a point index in target model .In the smpl-x model the correspondence should be (3377,3377).Could you understand?Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月9日(星期三) 晚上7:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Please always source what you say to help me helping you. Can you show the final correspondences.ply. How can I interpret the list you sent? What is supposed to be the ground truth?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-09 12:08
i want to get (qr,qt)like what the paper said
like following
![微信图片_20220209200821](https://user-images.githubusercontent.com/64821543/153198134-0f6e6c29-7eea-4707-9283-1bfd6e4e7bee.png)

**Comment by ThibaultGROUEIX** [comment] 2022-02-09 12:45
Ok I understand, but (3377,3375) may not be a bad pair of correspondences at all. What indication do you have that the predicted correspondences are very bad? Have you computed the L2 error for these correspondences?
What I mean by this is :
```
S : source vertices
T :  target vertices
S_u: vertex on S
T_u : ground truth correspondence on T
T_v: predicted correspondence on T
Compute the average over all pairs of L2(T_u, T_v)
```

**Comment by caijinana** [comment] 2022-02-10 13:30
![图片1](https://user-images.githubusercontent.com/64821543/153417756-0f3147e1-f730-4fcb-8560-5f7359e2bc24.png)
you can open the previous zip file,result_2.8.zip,and then open the all .ply file ,you will see the corresopndece point result ,like the picture,thank you very much

**Comment by caijinana** [comment] 2022-02-10 13:41
so i think (3377,3375)or(5404,4126)is a terrible result. @ThibaultGROUEIX

**Comment by caijinana** [comment] 2022-02-11 01:14
Sorry open .ply and .obj file



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月9日(星期三) 晚上8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Ok I understand, but (3377,3375) may not be a bad pair of correspondences at all. What indication do you have that the predicted correspondences are very bad? Have you computed the L2 error for these correspondences?
 What I mean by this is :
 S : source vertices T :  target vertices S_u: vertex on S T_u : ground truth correspondence on T T_v: predicted correspondence on T Compute the average over all pairs of L2(T_u, T_v)  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-11 12:30
Please address **all** points below and try to always be as clear as possible otherwise it is impossible to provide help.

1. I personally don't think there is evidence that the problem is on 3D-CODED side. It could also be your visualisation code AFAIK. This is the first thing we need to confirm.
2. Please run the quantitative evaluation described in my previous comment and share the code snippet and result.
3. Why did you share a screenshot with humans with holes ? Why should I infer from this image? What is it?
4. I don't see any ply files in your zip, see below. 
<img width="460" alt="Screenshot 2022-02-11 at 13 20 07" src="https://user-images.githubusercontent.com/11445067/153590432-fde3a438-8617-4fb9-8461-8397f27c1b2d.png">

Best regards,

**Comment by caijinana** [comment] 2022-02-11 13:46
is .obj file,sorry




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月11日(星期五) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Please address all points below and try to always be as clear as possible otherwise it is impossible to provide help.
  
I personally don't think there is evidence that the problem is 3D-CODED side. It could also be your visualisation code AFAIK. This is the first thing we need to confirm.
 
Please run the quantitative evaluation described in my previous comment and share the code snippet and result.
 
Why did you share a screenshot with humans with holes ? Why should I infer from this image? What is it?
 
I don't see any ply files in your zip, see below.
  

 
Best regards,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment] 2022-02-11 13:51
Sorry ,i means you can open the all.obj file,and the holes in the screenshor means correspondences points,like(3375,3375).
Best wishes,Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/3D-CODED"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Please address all points below and try to always be as clear as possible otherwise it is impossible to provide help.
  
I personally don't think there is evidence that the problem is 3D-CODED side. It could also be your visualisation code AFAIK. This is the first thing we need to confirm.
 
Please run the quantitative evaluation described in my previous comment and share the code snippet and result.
 
Why did you share a screenshot with humans with holes ? Why should I infer from this image? What is it?
 
I don't see any ply files in your zip, see below.
  

 
Best regards,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-11 17:03
Please address all  4 points as clearly as possible.

**Comment by caijinana** [comment] 2022-02-14 08:13
Thank you very much! I found my&nbsp;&nbsp;visualisation code AFAIK. i have get pretty good result!&nbsp;Happy Valentine's Day!Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/3D-CODED"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Please address all points below and try to always be as clear as possible otherwise it is impossible to provide help.
  
I personally don't think there is evidence that the problem is 3D-CODED side. It could also be your visualisation code AFAIK. This is the first thing we need to confirm.
 
Please run the quantitative evaluation described in my previous comment and share the code snippet and result.
 
Why did you share a screenshot with humans with holes ? Why should I infer from this image? What is it?
 
I don't see any ply files in your zip, see below.
  

 
Best regards,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-14 09:15
Hi @caijinana , I could not parse your previous comment. Can you please clarify what was the problem was to help others with the same bug?

**Comment by caijinana** [comment] 2022-02-14 09:17
Sure,When i finding the correspondence poin,i use 1 as the first point's index,however the fist point's index should be 0.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月14日(星期一) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Hi @caijinana , I could not parse your previous comment. Can you please clarify what was the problem was to help others with the same bug?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-14 09:18
Ok just to clarify : this comes from your own visualisation code ?

**Comment by caijinana** [comment] 2022-02-14 09:20
yes ,it's from my own visualisation code and my data.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月14日(星期一) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] how can i get the correspondence index? (Issue #46)





 
Ok just to clarify : this comes from your own visualisation code ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThibaultGROUEIX** [comment] 2022-02-14 09:20
Ok thanks, closing this then
Best regards
Thibault

**Closed as completed by ThibaultGROUEIX** 2022-02-14 09:20 UTC
